//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AramaSonuclari
    {
        public string UlkeAd { get; set; }
        public int EnerjiId { get; set; }
        public string EnerjiSinifi { get; set; }
        public Nullable<int> EnerjiDegeri { get; set; }
        public string EmisyonSinifi { get; set; }
        public Nullable<int> EmisyonDegeri { get; set; }
        public string EMail { get; set; }
        public string SirketIsmi { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Sifre { get; set; }
        public string TelefonNo { get; set; }
        public Nullable<bool> TelefonGorunsunMu { get; set; }
        public Nullable<int> CinsiyetTip { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<int> UyeTip { get; set; }
        public string GirisIp { get; set; }
        public Nullable<System.DateTime> SongirisTarihi { get; set; }
        public string IlanTipi { get; set; }
        public string BireyselIkiz { get; set; }
        public Nullable<int> KatNo { get; set; }
        public string MulkiyetTipi { get; set; }
        public string SehirAd { get; set; }
        public Nullable<int> PostaKodu { get; set; }
        public Nullable<int> OdaSayisi { get; set; }
        public string IcMekan { get; set; }
        public Nullable<int> KullanimAlani { get; set; }
        public Nullable<int> YatakOdaSayisi { get; set; }
        public Nullable<int> YasamAlani { get; set; }
        public string BosOlacagiTarih { get; set; }
        public Nullable<decimal> AylikKira { get; set; }
        public Nullable<int> BinaYasi { get; set; }
        public string Sokak { get; set; }
        public string Adres { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<decimal> KomisyonluSatisFiyati { get; set; }
        public string ReferansNo { get; set; }
        public Nullable<decimal> KiralikMasrafsiz { get; set; }
        public Nullable<decimal> KiralikMasrafli { get; set; }
        public Nullable<int> YayinlanmaSureId { get; set; }
        public Nullable<System.DateTime> YayinTarih { get; set; }
        public Nullable<System.DateTime> SonGuncellemeTarih { get; set; }
        public Nullable<int> YayinDurumTip { get; set; }
        public Nullable<bool> Sil { get; set; }
        public Nullable<int> UlkeId { get; set; }
        public int IlanId { get; set; }
        public Nullable<int> UyeId { get; set; }
        public int IlanFotografId { get; set; }
        public string Thumb { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnerjiSinifi
    {
        public int EnerjiId { get; set; }
        public string EnerjiSinifi1 { get; set; }
        public Nullable<int> EnerjiDegeri { get; set; }
        public string EmisyonSinifi { get; set; }
        public Nullable<int> EmisyonDegeri { get; set; }
        public Nullable<int> IlanId { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvAlanOzelikleri
    {
        public int EvAlanOzelikleriId { get; set; }
        public Nullable<int> KullanimAlani { get; set; }
        public Nullable<int> BinaYasi { get; set; }
        public Nullable<bool> MutfakEkipmani { get; set; }
        public Nullable<int> Dolaplar { get; set; }
        public string BahceKapisi { get; set; }
        public string Pencereler { get; set; }
        public string Panjurlar { get; set; }
        public string Cati { get; set; }
        public string CatiIskeleti { get; set; }
        public string DisKaplama { get; set; }
        public string BahceDuvari { get; set; }
        public Nullable<int> IlanId { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvGenelOzelikleri
    {
        public int EvGenelOzelikleriId { get; set; }
        public Nullable<System.DateTime> BosolacagiTarih { get; set; }
        public string MulkiyetDurumu { get; set; }
        public string OrtakKullanimDurumu { get; set; }
        public Nullable<decimal> YillikAidat { get; set; }
        public Nullable<bool> VideSanitaire { get; set; }
        public Nullable<int> IlanId { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FavoriIlan
    {
        public int FavoriIlanId { get; set; }
        public Nullable<int> UyeId { get; set; }
        public Nullable<int> IlanId { get; set; }
        public Nullable<System.DateTime> EklemeTarih { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class il
    {
        public int id { get; set; }
        public int ulke_id { get; set; }
        public string ad { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ilan
    {
        public int IlanId { get; set; }
        public string IlanBaslik { get; set; }
        public Nullable<int> UlkeId { get; set; }
        public string IlanTipi { get; set; }
        public string BireyselIkiz { get; set; }
        public Nullable<int> KatNo { get; set; }
        public string MulkiyetTipi { get; set; }
        public string SehirAd { get; set; }
        public Nullable<int> PostaKodu { get; set; }
        public string Asansor { get; set; }
        public string IcMekan { get; set; }
        public Nullable<int> OdaSayisi { get; set; }
        public Nullable<int> KullanimAlani { get; set; }
        public Nullable<int> YasamAlani { get; set; }
        public Nullable<int> YatakOdaSayisi { get; set; }
        public string BosOlacagiTarih { get; set; }
        public Nullable<decimal> AylikKira { get; set; }
        public Nullable<int> BinaYasi { get; set; }
        public string Sokak { get; set; }
        public string Adres { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<decimal> KomisyonluSatisFiyati { get; set; }
        public string ReferansNo { get; set; }
        public Nullable<decimal> KiralikMasrafsiz { get; set; }
        public Nullable<decimal> KiralikMasrafli { get; set; }
        public Nullable<int> YayinlanmaSureId { get; set; }
        public Nullable<System.DateTime> YayinTarih { get; set; }
        public Nullable<System.DateTime> SonGuncellemeTarih { get; set; }
        public Nullable<int> YayinDurumTip { get; set; }
        public Nullable<int> UyeId { get; set; }
        public Nullable<bool> Sil { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IlanDetay
    {
        public int IlanDetayId { get; set; }
        public string MGenelDurum { get; set; }
        public string OKullanimDurum { get; set; }
        public string BahceKapisi { get; set; }
        public string BahceKapisiDurumu { get; set; }
        public string Panjurlar { get; set; }
        public string Pencereler { get; set; }
        public string Dolaplar { get; set; }
        public Nullable<decimal> YillikAidat { get; set; }
        public Nullable<decimal> YillikVergiler { get; set; }
        public Nullable<bool> MutfakEkipManlari { get; set; }
        public Nullable<bool> Interphone { get; set; }
        public Nullable<bool> Alarm { get; set; }
        public Nullable<bool> Uydu { get; set; }
        public Nullable<bool> AntenTv { get; set; }
        public Nullable<bool> SomineTip1 { get; set; }
        public Nullable<bool> SomineTip2 { get; set; }
        public string CatiKati { get; set; }
        public string GiyinmeOdasi { get; set; }
        public string Kiler { get; set; }
        public string CatiDurum { get; set; }
        public string DisKaplamaDurum { get; set; }
        public string CatiIskeletiDurum { get; set; }
        public string Bodrum { get; set; }
        public string Garaj { get; set; }
        public string ParkYeri { get; set; }
        public string Havuz { get; set; }
        public string BahceDuvari { get; set; }
        public string SuOlcumleri { get; set; }
        public string IlanAciklama { get; set; }
        public Nullable<int> IlanId { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IlanFotograf
    {
        public int IlanFotografId { get; set; }
        public Nullable<int> IlanId { get; set; }
        public string FotoPath { get; set; }
        public string Thumb { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IlanIletisim
    {
        public int IlanIletisimId { get; set; }
        public string IlanEmail { get; set; }
        public string IlanTelefon { get; set; }
        public string IlanTelefon2 { get; set; }
        public string IlanIletisimSekli { get; set; }
        public string IlanIletisimSaatleri { get; set; }
        public Nullable<int> IlanId { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Isinma
    {
        public int IsınmaId { get; set; }
        public string GenelDurum { get; set; }
        public Nullable<int> IsiSistemleriYasi { get; set; }
        public string Isitma { get; set; }
        public string IsinmaTipi { get; set; }
        public string EnerjiTipi { get; set; }
        public Nullable<decimal> YillikTuketim { get; set; }
        public Nullable<int> IlanId { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KonutDetay
    {
        public int KonutDetayId { get; set; }
        public Nullable<int> m2 { get; set; }
        public string Kat { get; set; }
        public string Yon { get; set; }
        public string YerDoseme { get; set; }
        public string Cerceveler { get; set; }
        public string Camlar { get; set; }
        public string Panjur { get; set; }
        public int IlanId { get; set; }
        public string Odalar { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OdemeListesi
    {
        public int OdemeId { get; set; }
        public string PaketAdi { get; set; }
        public int UyeId { get; set; }
        public int MiktarId { get; set; }
        public System.DateTime OdemeTarihi { get; set; }
        public bool Durumu { get; set; }
        public bool Sil { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sayfalar
    {
        public int SayfaId { get; set; }
        public string SayfaAdi { get; set; }
        public string SayfaAciklama { get; set; }
        public string Icerik { get; set; }
        public Nullable<bool> Onay { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teshisler
    {
        public int TeshisId { get; set; }
        public Nullable<bool> Asbest { get; set; }
        public Nullable<bool> Termit { get; set; }
        public Nullable<bool> Kursun { get; set; }
        public Nullable<bool> Carrez { get; set; }
        public Nullable<bool> Electrik { get; set; }
        public Nullable<bool> Gaz { get; set; }
        public Nullable<int> IlanId { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ulke
    {
        public int id { get; set; }
        public string UlkeAd { get; set; }
    }
}
namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uye
    {
        public int UyeId { get; set; }
        public string EMail { get; set; }
        public string SirketIsmi { get; set; }
        public string Siren { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Sifre { get; set; }
        public Nullable<bool> TelefonGorunsunMu { get; set; }
        public string TelefonNo { get; set; }
        public string Adres { get; set; }
        public Nullable<int> UlkeId { get; set; }
        public string SehirAd { get; set; }
        public Nullable<int> IlceId { get; set; }
        public Nullable<int> CinsiyetTip { get; set; }
        public Nullable<System.DateTime> KayitTarih { get; set; }
        public Nullable<bool> Sil { get; set; }
        public Nullable<int> UyeTip { get; set; }
        public Nullable<int> PostaKodu { get; set; }
        public string GirisIp { get; set; }
        public Nullable<System.DateTime> SongirisTarihi { get; set; }
    }
}
