//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class adhibeEntities : DbContext
    {
        public adhibeEntities()
            : base("name=adhibeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EnerjiSinifi> EnerjiSinifis { get; set; }
        public virtual DbSet<EvAlanOzelikleri> EvAlanOzelikleris { get; set; }
        public virtual DbSet<EvGenelOzelikleri> EvGenelOzelikleris { get; set; }
        public virtual DbSet<il> ils { get; set; }
        public virtual DbSet<IlanFotograf> IlanFotografs { get; set; }
        public virtual DbSet<Isinma> Isinmas { get; set; }
        public virtual DbSet<KonutDetay> KonutDetays { get; set; }
        public virtual DbSet<OdemeListesi> OdemeListesis { get; set; }
        public virtual DbSet<Sayfalar> Sayfalars { get; set; }
        public virtual DbSet<Teshisler> Teshislers { get; set; }
        public virtual DbSet<IlanIletisim> IlanIletisims { get; set; }
        public virtual DbSet<FavoriIlan> FavoriIlans { get; set; }
        public virtual DbSet<AramaSonuclari> AramaSonuclaris { get; set; }
        public virtual DbSet<ulke> ulkes { get; set; }
        public virtual DbSet<Ilan> Ilans { get; set; }
        public virtual DbSet<Uye> Uyes { get; set; }
        public virtual DbSet<IlanDetay> IlanDetays { get; set; }
    }
}
